### ISSUE TITLE
Todo Lists

### ISSUE THREAD

**Issue by alvinseptiano** [UNPAM-04TPLP02/LendABook#1]
- [ ] Database
  + [ ] Add search feature
  + [X] Store user data
  + [ ] Store user's book
- [ ] GUI
  + [ ] PinjamUI
  + [ ] EditUI
- [ ] Buat script dan presentasi program
